### ISSUE TITLE
Dysentery classification showing correctly but Very severe disease also showing up with it.

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare#12]
Tested for Patient 65
![Screenshot_20230131_121441_EmCare](https://user-images.githubusercontent.com/122801361/215686443-2c1b9d96-30cd-4875-904d-ae6f23d5c998.jpg)

**Comment by delcroip** [comment]
here the logic I have for very severe disease 



C."child"
AND 
(
"Convulsing Now" = true and  "Continue to Assess Sick Child" = "Stabilised, continue consultation" or
"Convulsion(s) in this Illness" = true or
"Unconscious" = true or
"Lethargic" = true or
"Oral Fluid Test Results" = "Completely Unable to Drink" or
"Oral Fluid Test Results" = "Vomits Immediately / Everything" or
)

did you had any of those ?

**Comment by kaledip** [comment]
> here the logic I have for very severe disease
> 
> C."child" AND ( "Convulsing Now" = true and "Continue to Assess Sick Child" = "Stabilised, continue consultation" or "Convulsion(s) in this Illness" = true or "Unconscious" = true or "Lethargic" = true or "Oral Fluid Test Results" = "Completely Unable to Drink" or "Oral Fluid Test Results" = "Vomits Immediately / Everything" or )
> 
> did you had any of those ?

No . I had not selected these options.

**Comment by delcroip** [comment]
is it still the case with build8 ?

**Comment by kaledip** [comment]
I need to retest this and let you know.

**Comment by kaledip** [comment]
working fine now.
