### ISSUE TITLE
Fast breathing for YI is wrongly calculated

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare#130]
For YI anything above 60 is fast breathing. If I enter 55 then also it shows Fast breathing as Yes

**Comment by delcroip** [comment]
The limit was 50 in version 4 but 60 in version 60, please confirm what is the limit

**Comment by kaledip** [comment]
This is the correct logic:
"Fast breathing is auto-calculated based on the respiratory rate and the child's age: 
- Under 2 months: More than 60 breaths per minute*
- 2 to 11 months: More than 50 breaths per minute
- 12 to 59 months: More than 40 breaths per minute

*In young infants, a second measurement should be taken to confirm, unless there is already another sign of possible serious bacterial infection"

**Comment by kaledip** [comment]
Retested and working
