### ISSUE TITLE
Older child specific danger signs are appearing for YI

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare#131]

**Comment by delcroip** [comment]
Danger sign should only be triggered for > 2 m @kaledip  please confirm

**Comment by kaledip** [comment]
> Danger sign should only be triggered for > 2 m @kaledip please confirm

"Convulsing Now'" is a danger sign that is applicable for both age groups. But the rest are only for older child.

**Comment by delcroip** [comment]
duplicate of #70

**Comment by kaledip** [comment]
Not yet working.
