### ISSUE TITLE
Axillary Temperature (second measurement) (degrees Celcius) not being prompted for YI

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare#133]
The first temperature entered was 38 which is High and still second temp was not prompted in assessments.

**Comment by delcroip** [comment]
I tested it and it worked

**Comment by kaledip** [comment]
Not working for me I am adding axillary temp as 38 (high) and no other positive signs. So PBSI other than temp != true and temp = high. Tested for patient ID P 777.
Do let me know if yo need more details to debug

**Comment by kaledip** [comment]
@delcroip app crashing on classification when I enter the second temp measurement.

**Comment by kaledip** [comment]
Retested and working fine.
