### ISSUE TITLE
Inhaled Bronchodilator Trial test issues

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare#135]
1. The fast breathing element needs to be autocalculated
2. Respiratory rate needs to be a quantity field
3. Chest indrawing to be a boolean

right now all fields appearing as check boxes
![Screenshot_20230404_141138_EmCare Dev (1)](https://user-images.githubusercontent.com/122801361/229739432-feaa1e88-93be-4e93-aad6-1824bdb56e17.jpg)

**Comment by kaledip** [comment]
Not yet working as expected. Respiratory rate should be a quanity field and fast breathing an auto calculated one.

![Image](https://user-images.githubusercontent.com/122801361/234188585-1eae5dbf-98e2-4534-b1ff-f18b298f8561.jpeg)

**Comment by delcroip** [comment]
Are you sure you updated the app ?

**Comment by kaledip** [comment]
@delcroip  tested with build 578
The last element also needs to be auto calculated . The Yes and No on it do not appear highlighted.


![Image](https://user-images.githubusercontent.com/122801361/235107282-6199c6c3-a939-48a2-af61-8fcf9c844817.jpg)

**Comment by kaledip** [comment]
@delcroip  Fast breathing is now correctly calculcated but the element "No fast breathing and no chest indrawing" is also a autocalulated element . Needs to look like fast breathing one.

**Comment by delcroip** [comment]
fixed but the first question looks odd "Chest Indrawing (post inhaled bronchodilator trial)"

**Comment by kaledip** [comment]
@delcroip  We discussed that test should appear eventhough Oxygen saturation is left unanswered. 
Only that point is pending otherwise working fine.

**Comment by delcroip** [comment]
fixed in v726, the root cause was a systemic issue on the structure map that was not saving properly the checkbox as "cannot merasure ... " in observation, I am sure other issue will be fixed too

**Comment by kaledip** [comment]
Retested on prod.Working fine
