### ISSUE TITLE
Can we separate clinical indicators and system indicators

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare#137]

**Comment by kaledip** [comment]
Indicators like total user, Pending user request are more of admin level indicators
Indicators in file are clinical indicators
Can we have a separation in view, or rather do we need separation @haskewc to confirm

**Comment by jkalariya** [comment]
@kaledip  Issue Resolved

**Comment by kaledip** [comment]
These are now separated
