### ISSUE TITLE
Line chart- Can we show start date instead of just no of weeks

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare#138]

**Comment by kaledip** [comment]
Its a bit confusing when it says April 2023 but shows no of weeks uptill 12

![Image](https://user-images.githubusercontent.com/122801361/230294557-0a8363e5-6f45-494a-be14-02ed4c12704e.png)

**Comment by jkalariya** [comment]
@kaledip Issue Resolved
