### ISSUE TITLE
Pneumonia classification not showing correctly

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare#14]
Pneumonia classification not showing up. Inputs selected are
Cough = Yes, Wheezing =No, Chest indrawing= Yes.

tested for Patient 65

**Comment by delcroip** [comment]
Indeed it should works, here the current loigic

C."age >= 2 months to <60 months" and ("Cough"= true  or  o"Difficulty Breathing" = true) and (o"Fast breathing" = true or  o"Chest indrawing" = true) and ("Severe Pneumonia or Very Severe Disease" = false ) and 
(
o"Wheezing" = false
or
( o"Wheezing" = true)  and  (o"Inhaled Bronchodilator Trial Not Feasible or Available"=true or o"Chest Indrawing (post inhaled bronchodilator trial)"=true or   o"Fast Breathing (post inhaled bronchodilator trial)"=true)
)

I will double check

**Comment by delcroip** [comment]
Found the issue "Severe Pneumonia or Very Severe Disease" = false should be "Severe Pneumonia or Very Severe Disease" != true BUT please check the code of Pneumonia because there is another code in classification <2

**Comment by kaledip** [comment]
> Found the issue "Severe Pneumonia or Very Severe Disease" = false should be "Severe Pneumonia or Very Severe Disease" != true BUT please check the code of Pneumonia because there is another code in classification <2

@delcroip By code you men the decision logic right? The logic to reach a classification can be different for each age group.

**Comment by delcroip** [comment]
No simply the data elements id

**Comment by kaledip** [comment]
> No simply the data elements id

The element ID is same as 06 for both Pneumonia. I will double check too.

**Comment by kaledip** [comment]
Retested and getting Pneumonia now. But treatments is blank

**Comment by delcroip** [comment]
it works for me

**Comment by kaledip** [comment]
It works now but treatment is not properly formatted.
