### ISSUE TITLE
Some dehydration showing instead of Severe dehydration

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare#150]
Diarrhoea= Yes
and 
("Sunken Eyes" = "Yes"
and
"Oral Fluid Test Results" = "Drinks Poorly")

Expected classification = Severe Dehydration
Classification displayed = Some dehydration

**Comment by delcroip** [comment]
YI or child ?

**Comment by delcroip** [comment]
/* 
DL-G-CL1-23-30 : 
    ("Diarrhoea" = true)
     and ((    ("Age >= 2 months to <60 months")
         and ((    "Unconscious" = true and "Skin pinch of Abdomen" = "Skin Pinch goes back slowly (2 seconds or fewer, but not immediately)")
         or (    ("Restless and Irritable" = true or "Skin pinch of Abdomen" = "Skin Pinch goes back slowly (2 seconds or fewer, but not immediately)" ) and ("Oral Fluid Test Results" = "Completely Unable to Drink" or "Oral Fluid Test Results" = "Vomits Immediately / Everything" or  "Completely Unable to Drink or Vomits Immediately / Everything"=true))
         or (    (ToInteger("Unconscious or Lethargic" = true) + ToInteger("Sunken Eyes" = true) +ToInteger("Skin pinch of Abdomen" = "Skin Pinch goes back very slowly (More than 2 seconds)" )+ToInteger( "Oral Fluid Test Results" = "Completely Unable to Drink" )+ToInteger(  "Oral Fluid Test Results" = "Vomits Immediately / Everything")  + ToInteger(  "Completely Unable to Drink or Vomits Immediately / Everything"=true )+ToInteger( "Oral Fluid Test Results" = "Drinks Poorly") )>1)))
     or (    (AgeInMonths()<2)
         and ((    (ToInteger("Sunken Eyes"=true) +  ToInteger("Skin pinch of Abdomen" = "Skin Pinch goes back very slowly (More than 2 seconds)") + ToInteger("Movements" = "Movement only when stimulated but then stops") +ToInteger("Movements" = "No movement at all"))>1)
         or (    "Skin pinch of Abdomen" = "Skin Pinch goes back very slowly (More than 2 seconds)" and ("Movements" = "Movement only when stimulated but then stops"  or "Movements" = "No movement at all" )))))
*/

the CQL seems correct

**Comment by kaledip** [comment]
@delcroip  this is for older child

**Comment by delcroip** [comment]
I think this is solved with the fix for second temp (bad CQL syntax was used)

**Comment by kaledip** [comment]
Retested but not working yet

![Image](https://github.com/WorldHealthOrganization/smart-emcare/assets/122801361/2a717502-f5be-489f-9854-e46b4efa8713)

**Comment by kaledip** [comment]
Tested and looks ok.
