### ISSUE TITLE
PSBI classification for YI

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare#155]
Age <2 months and Hot to touch = true
Expected classification= VSD or PSBI 
Classification displayed: Infection unlikely

![Image](https://user-images.githubusercontent.com/122801361/235637991-39d82338-ed43-4f15-9065-740d6cb39d35.jpg)

![Image](https://user-images.githubusercontent.com/122801361/235638027-7e575390-83a8-4a0f-b3d0-c33e6816fb31.jpg)

**Comment by kaledip** [comment]
Scenario 2:

age<2 months Measured temp = high then PSBI not not being displayed

**Comment by delcroip** [comment]
Senario 2 should be fixed

**Comment by kaledip** [comment]
Tested on prod .Working now
