### ISSUE TITLE
Instance observed that second dropdown on questionnaire gets populated with value selected in first dropdown

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare#16]
I selected "Estimated dat of birth" in first dropdown then second dropdown question is about "Primary caregiver's relation". That dropdown was also populated by the value in first dropdown.

@kunjan8794 can you please check if this is an L4 issue.
@delcroip Few questions in caregiver section need to be updated as per latest DAK.

Attaching screenshots for reference.
![Screenshot_20230131_131252_EmCare](https://user-images.githubusercontent.com/122801361/215698223-e5cc760e-6d91-477a-bb99-e11e5f93c82e.jpg)
![Screenshot_20230131_131243_EmCare](https://user-images.githubusercontent.com/122801361/215698251-3b1f2fa6-d231-4168-b22f-3ee19f49f295.jpg)

**Comment by delcroip** [comment]
@kaledip  can you rested as the options are not pulled in the same way it might impact this issue

**Comment by ppanchal-argus** [comment]
It was a bug in SDC, might be present in version 1.0.8 but on dev release it is resolved.
@kaledip you can retest on the current dev version or in next release 1.0.9.

Issue: https://github.com/google/android-fhir/issues/1775

**Comment by kaledip** [comment]
Retested on 14th feb. working ok.
