### ISSUE TITLE
Severe jaundice and prolonged jaundice not reached for a certain pathway (YI)

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare#163]
Tested on v1.1.2 build 611

Age is < 2 months, Yellow skin= No and "Yellow palms or yellow soles"= Yes
Expected classification: Severe Jaundice
Classification reached: Infection unlikely

Age > 21 days Yellow skin= Yes
Expected classifiation: Prolonged jaundice
Classification reached: Infection unlikely

**Comment by delcroip** [comment]
2 nd case not alligned with DAK, <24 hours, I tried with a YI born the same day and it works

**Comment by kaledip** [comment]
second case refers to row DL-G-CL2-16.
scenario 1 is working now

**Comment by delcroip** [comment]
Second case is for jaundice/ with prolonged jaundice   and it should work

**Comment by kaledip** [comment]
@delcroip Not getting Prolonged jaundice. Tested with bundle 1.0.2build45

![Image](https://github.com/WorldHealthOrganization/smart-emcare/assets/122801361/55f9c634-30a9-4c2a-b474-8e2d04a71e87)

**Comment by delcroip** [comment]
works now (prolonged jaundice as qualifier)

**Comment by kaledip** [comment]
Retested on dev. Works ok
