### ISSUE TITLE
Severe Dehydration for YI not working for mentioned three pathway

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare#169]
Tested with v1.1.2 build 611

Pathway 1 : Inputs as below:
"Age" = "<2 months"	
"Diarrhoea" = "Yes"	
"Skin Pinch of Abdomen" = "Goes back slowly (2 seconds or fewer, but not immediately)"	
"Movements" = "Movement only when Stimulated but then stops" 

Pathway 2 : Inputs as below:
"Age" = "<2 months"	
"Diarrhoea" = "Yes"	
"Skin Pinch of Abdomen" = "Goes back slowly (2 seconds or fewer, but not immediately)"	
"Movements" = "No Movement at all"

Pathway 3 : Inputs as below:
"Age" = "<2 months"	
"Diarrhoea" = "Yes"
"Skin Pinch of Abdomen" = "Goes back very slowly (More than 2 seconds)"	
"Restless and Irritable" = "Yes"

**Comment by delcroip** [comment]
should be solved with 2nd temp measurement

**Comment by kaledip** [comment]
This is not yet working , not getting the classification

**Comment by kaledip** [comment]
Working for first 2 scenarios but failing for third scenario

**Comment by delcroip** [comment]
scenario 1 & 2 OK, issue found for 3 (to be fixed in the next bundle)

**Comment by delcroip** [comment]
scenario 3 OK

**Comment by kaledip** [comment]
Tested for scenario 3 also. Working fine. Thanks
