### ISSUE TITLE
Very severe disease not appearing 

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare#17]
I selected "Convulsing now"= Yes then "Continue to Assess Sick Child" = "Stabilised, continue consultation" 
Output expected was Very severe disease but it is not showing up.

**Comment by kaledip** [comment]
{"resourceType":"Bundle","entry":[{"resource":{"resourceType":"QuestionnaireResponse","questionnaire":"https://fhir.dk.swisstph-mis.ch/matchbox/fhir/Questionnaire/emcare.b23.classification","subject":{"reference":"Patient/8e7cc96c-c789-468a-86f2-9eeec9df7403","type":"Patient","identifier":{"value":"8e7cc96c-c789-468a-86f2-9eeec9df7403"}},"encounter":{"id":"8809fa1b-4fa2-4d4e-9a64-46a3ba300c78","reference":"Encounter/8809fa1b-4fa2-4d4e-9a64-46a3ba300c78","type":"Encounter","identifier":{"value":"8809fa1b-4fa2-4d4e-9a64-46a3ba300c78"}},"item":[{"linkId":"DL-XXXX"},{"linkId":"DL-G-CL1-07","text":"Severe Pneumonia or Very Severe Disease","answer":[{"valueBoolean":false}]},{"linkId":"EmCare.B23.DE04","answer":[{"valueBoolean":false}]},{"linkId":"EmCare.B23.DE05"},{"linkId":"EmCare.B23.DE08"},{"linkId":"Measles in last 3 months","answer":[{"valueBoolean":false}]},{"linkId":"DL-G-CL1-14","text":"Pneumonia","answer":[{"valueBoolean":false}]},{"linkId":"DL-G-CL1-19","text":"Cough or Cold","answer":[{"valueBoolean":false}]},{"linkId":"DL-G-CL1-23-30","text":"Severe Dehydration","answer":[{"valueBoolean":false}]},{"linkId":"DL-G-CL1-24-32","text":"Some Dehydration","answer":[{"valueBoolean":false}]},{"linkId":"DL-G-CL1-30","text":"No Dehydration","answer":[{"valueBoolean":false}]},{"linkId":"DL-G-CL1-31","text":"Severe Persistent Diarrhoea","answer":[{"valueBoolean":false}]},{"linkId":"DL-G-CL1-32","text":"Persistent Diarrhoea","answer":[{"valueBoolean":false}]},{"linkId":"DL-G-CL1-33","text":"Dysentery","answer":[{"valueBoolean":false}]},{"linkId":"DL-I-CL1-01","text":"Possible Shigella","answer":[{"valueBoolean":false}]},{"linkId":"DL-I-CL1-05","text":"Throat Abscess or Possible Diptheria","answer":[{"valueBoolean":false}]},{"linkId":"DL-I-CL1-06","text":"Streptococcal Sore Throat","answer":[{"valueBoolean":false}]},{"linkId":"DL-I-CL1-07","text":"Non-Streptococcal Sore Throat","answer":[{"valueBoolean":false}]},{"linkId":"DL-I-CL1-09","text":"No Throat Problem","answer":[{"valueBoolean":false}]},{"linkId":"DL-G-CL1-73","text":"Mastoiditis","answer":[{"valueBoolean":false}]},{"linkId":"DL-G-CL1-74-76","text":"Acute Ear Infection","answer":[{"valueBoolean":false}]},{"linkId":"DL-I-CL1-11-12","text":"Chronic Ear Infection","answer":[{"valueBoolean":false}]},{"linkId":"EmCare.B23.DE32a"},{"linkId":"DL-G-CL1-79","text":"No Ear Infection","answer":[{"valueBoolean":false}]},{"linkId":"DL-G-CL1-34","text":"Very Severe Febrile Disease"},{"linkId":"DL-I-CL1-03","text":"Fever: possible bacterial infection"},{"linkId":"EmCare.B23.DE26a","text":"Fever present every day for 7 Days or more","answer":[{"valueBoolean":false}]},{"linkId":"DL-I-CL1-26","text":"Fever: bacterial infection unlikely"},{"linkId":"DL-I-CL1-16-67a","text":"Severe Complicated Measles"},{"linkId":"DL-G-CL1-68-70","text":"Measles with Eye or Mouth Complication"},{"linkId":"DL-G-CL1-71","text":"Possible Measles"},{"linkId":"DL-G-CL1-109","text":"Severe Anaemia"},{"linkId":"DL-G-CL1-110","text":"Anaemia"},{"linkId":"DL-G-CL1-111","text":"No Anaemia","answer":[{"valueBoolean":false}]},{"linkId":"DL-G-CL1-80","text":"Eye Infection","answer":[{"valueBoolean":false}]},{"linkId":"DL-G-CL1-83","text":"Clouding of the Cornea","answer":[{"valueBoolean":false}]},{"linkId":"EmCare.B23.DE36","text":"New or not previously treated"},{"linkId":"DL-G-CL1-88","text":"Papular Urticaria or Papular Pruritic Eruptions"},{"linkId":"DL-G-CL1-90","text":"Ringworm (Tinea)"},{"linkId":"EmCare.B23.DE43a","text":"Scalp Infection (tinea capitis)"},{"linkId":"DL-G-CL1-91","text":"Scabies"},{"linkId":"DL-G-CL1-93","text":"Chickenpox"},{"linkId":"EmCare.B23.DE46A"},{"linkId":"EmCare.B23.DE46","answer":[{"valueBoolean":false}]},{"linkId":"DL-G-CL1-95","text":"Herpes Zoster"},{"linkId":"EmCare.B23.DE48"},{"linkId":"EmCare.B23.DE48a"},{"linkId":"DL-G-CL1-98","text":"Impetigo"},{"linkId":"EmCare.B23.DE50"},{"linkId":"EmCare.B23.DE50a"},{"linkId":"DL-G-CL1-99","text":"Molluscum Contagiosum"},{"linkId":"EmCare.B23.DE52a"},{"linkId":"DL-G-CL1-100","text":"Warts"},{"linkId":"EmCare.B23.DE53a"},{"linkId":"DL-G-CL1-102","text":"Seborrhoeic Dermatitis"},{"linkId":"EmCare.B23.DE55"},{"linkId":"DL-G-CL1-103"},{"linkId":"DL-G-CL1-104"},{"linkId":"EmCare.B23.DE57a"},{"linkId":"EmCare.B23.DE57b"},{"linkId":"EmCare.B23.DE57c"},{"linkId":"DL-G-CL1-105","text":"Steven Johnson Syndrome (SJS)"},{"linkId":"DL-G-CL1-106","text":"Mouth Sores or Ulcer","answer":[{"valueBoolean":false}]},{"linkId":"EmCare.B23.DE60","answer":[{"valueBoolean":false}]},{"linkId":"DL-G-CL1-108","text":"Oral Thrush","answer":[{"valueBoolean":false}]},{"linkId":"DL-I-CL1-28","text":"Very Low Weight for Age","answer":[{"valueBoolean":false}]},{"linkId":"DL-I-CL1-33","text":"Low Weight for Age","answer":[{"valueBoolean":false}]},{"linkId":"DL-I-CL1-34","text":"Low MUAC or visual report of wasting","answer":[{"valueBoolean":false}]},{"linkId":"collector","text":"Add other classifications"},{"linkId":"timestamp"}]}},{"resource":{"resourceType":"Patient","id":"8e7cc96c-c789-468a-86f2-9eeec9df7403","meta":{"versionId":"1","lastUpdated":"2023-02-02T10:07:53.630+00:00"},"extension":[{"url":"http://hl7.org/fhir/StructureDefinition/patient-locationId","valueIdentifier":{"use":"official","value":"ea5f0cab-b493-42ec-815c-a1f52d6b9552"}}],"identifier":[{"use":"official","value":"P70"}],"name":[{"use":"official","family":"70","given":["Patient"]}],"gender":"female","birthDate":"2022-02-16"}}]}

**Comment by delcroip** [comment]
same as #20
