### ISSUE TITLE
Visually assess for whether underweight (for drug dose calculation) not appearing in measurements

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare#170]
MUAC is left null or not answered. then we should get the question of 
Visually assess for whether underweight (for drug dose calculation)..

But the question does not appear.

**Comment by kaledip** [comment]
Que not appearing yet. Build 681

![Image](https://github.com/WorldHealthOrganization/smart-emcare/assets/122801361/3a2a6575-dd06-4e89-80b8-ca644b6d2bbb)

**Comment by delcroip** [comment]
wrong enableWhenExpression , int was check against quantity

**Comment by delcroip** [comment]
diplayed is "MUAC cannot ... " checked

**Comment by kaledip** [comment]
The question is appearing but not able to submit and proceed to Symptoms stage.


![Image](https://github.com/WorldHealthOrganization/smart-emcare/assets/122801361/cb93fd2f-a6aa-40d2-ba6d-ba078d657ece)

**Comment by delcroip** [comment]
Did you select a choice ?

**Comment by delcroip** [comment]
the new issue is a duplicate of #180 so please @kaledip  close this one
