### ISSUE TITLE
Migrate IG to https://github.com/WorldHealthOrganization/smart-ig-starter-kit

### ISSUE THREAD

**Issue by delcroip** [WorldHealthOrganization/smart-emcare#212]
Context:
-  smart-emcare is using an old IG template, it must be replaced by the new https://github.com/WorldHealthOrganization/smart-ig-starter-kit
Task:

- [ ] create branch `smart-ig-starter-kit` 
- [ ] update the file structure to match  https://github.com/WorldHealthOrganization/smart-ig-starter-kit
- [ ] make sure pyfhirsdc is updated if required
- [ ] migrate the 'documentation' part 
- [ ] test that the IG can be created using the github actions

**Comment by rukshn** [comment]
The current IG is now based on the new smart IG template. Therefore I would be closing this issue.,
