### ISSUE TITLE
Treatments not displaying with one line per treatment

### ISSUE THREAD

**Issue by gillianlevine** [WorldHealthOrganization/smart-emcare#32]
The treatments are displaying with multiple different treatments one one line, separated by a dot. This is incorrect and difficult for the user to interpret. Each different treatment (as separated by a dot) must be displayed on a separate line to be interpreted correctly.

**Comment by delcroip** [comment]
@kaledip do you have that issue  ?

**Comment by kaledip** [comment]
Yes I have observed this in a coupe of treatments.

**Comment by delcroip** [comment]
Should be ok now (I think I found the root cause but I did not experience it  myself)

**Comment by kaledip** [comment]
This is resolved
