### ISSUE TITLE
Response options displayed in a manner that is confusing to users

### ISSUE THREAD

**Issue by gillianlevine** [WorldHealthOrganization/smart-emcare#38]
Relative to the questions, the size of the response option buttons is way too large. It is difficult for the user to even see what the question is they are responding to when the size of the options is so much larger than the question type. Additionally, sometimes the response options are grey, which is generally understood to be not available/not an option, and sometimes they are black. It needs to be consistent. For some questions, there are optional check boxes that can be selected, but then for others a check box must be selected, and these are still displayed is grey, which is again inconsistent across question items. When there are multiple check box items, they are very small, while the option buttons and drop downs are very large. This inconsistency makes it hard for users to know what they are supposed to be answering, what is a question, what is a response, what is mandatory and what isn't and what needs to be answered and what is not mandatory.

**Comment by ppanchal-argus** [comment]
@gillianlevine currently we are working on making the font sizes dynamic in the questionnaire which will help on this. Thanks for the feedback we will look into these issues along with it!

**Comment by ppanchal-argus** [comment]
Dynamic font size is supported now, let me know if you've any additional feedback on this, can be retested in v1.0.10

**Comment by kaledip** [comment]
![Image](https://user-images.githubusercontent.com/122801361/226333949-06ee43cd-5cfb-4fb3-9508-fe906a0842b8.png)

**Comment by kaledip** [comment]
@ppanchal-argus  the answer options for feeding difficulty are of different size. So this is yet to be resolved

**Comment by delcroip** [comment]
Done

**Comment by kaledip** [comment]
Retested and closed
