### ISSUE TITLE
 "Classification" = "EmCare.B23.DE27 - Severe Complicated Measles" not showing

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare#4]
<html>
<body>
<div ccp_infra_version='3' ccp_infra_timestamp='1673942734843' ccp_infra_user_hash='656267598' ccp_infra_copy_id='cce1ab3d-f229-47c2-826a-f5a42dda98c1' data-ccp-timestamp='1673942734843'><html><head><meta name=ProgId content=Excel.Sheet><meta name=Generator content="Microsoft Excel 15"><style>table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
td
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	text-align:general;
	vertical-align:bottom;
	border:none;
	white-space:nowrap;
	mso-rotate:0;}
.xl38
	{border-top:.5pt solid black;
	border-right:.5pt solid black;
	border-bottom:none;
	border-left:.5pt solid black;
	white-space:normal;}
</style></head><body link="#0563C1" vlink="#954F72">

"Classification" = "EmCare.B23.DE27 - Severe Complicated Measles" not showing
--

</body></html></div>
</body>
</html>

**Comment by delcroip** [comment]
Root cause: 
I thought that I needed to check that the Patient had a recorded measles conditions in the pas 3 months

I kept that approach + the observation "Measles within the last 3 months"

**Comment by kaledip** [comment]
I retested this and was able t reach Severe complicated measles classification.
