### ISSUE TITLE
Unable to put decimals for weight and MUAC

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare#49]

**Comment by ppanchal-argus** [comment]
unable to find the MUAC, but you are able to enter decimals for weight in measurements. Let me know if there is any other questionnaire I should look into.

**Comment by kaledip** [comment]
> @kaledip unable to find the MUAC, but we are able to enter decimals for weight in measurements. Let me know if there is any other questionnaire I should look into.

MUAC is in the measurement questionnaire. It appears if weight/length not provided. Also I am not able to add decimals for weight.

**Comment by kaledip** [comment]
@ppanchal-argus  can you please tell me which bundle/build I should check this in?

**Comment by ppanchal-argus** [comment]
@kaledip In the latest dev version this should be working.
![Screenshot_20230411_232840_EmCare Dev](https://user-images.githubusercontent.com/99809012/231370245-cedb4098-a768-4b56-b8a6-022dd7ae226c.jpg)

**Comment by delcroip** [comment]
@ppanchal-argus  I understood that this one was fixed, isn't it ?

**Comment by ppanchal-argus** [comment]
@delcroip Yes, you're right! It was fixed. The issue was with samsung keyboard in particular, that it didn't show up decimal. Which is why it was firstly wrongly flagged as done. I'll update the issue status!
