### ISSUE TITLE
Classification not showing Fever:bacterial infection unlikely with qualifier.

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare#51]
"Identify "Classification" = "EmCare.B23.DE105 - Fever: bacterial infection unlikely"  "Classification - Qualifier" = "EmCare.B23.DE26a - Fever present every day for more than 7 days""

Inputs applied:
"Fever" = "Yes" and "Fever for how long?" = "More than 7 days"	and "Has Fever been present every day for more than 7 days" = "Yes"

**Comment by delcroip** [comment]
this is my definition of "bacterial infection unlikely "

C."age >= 2 months to <60 months" and C."fever" = true and ( "Streptococcal Sore Throat"!=true  or "Pneumonia"!=true or "Acute Ear Infection"!=true  or  "Chronic Ear Infection"!=true or  "Dysentery"!=true) and "Possible Shigella"!=true and  "Throat Abscess or Possible Diptheria"!=true and "Severe Complicated Measles"!=true and "Measles with Eye or Mouth Complication"!=true and "Possible Measles"!=true and  "Mastoiditis"!=true and "Very Severe Febrile Disease"!=true and  "Severe Pneumonia or Very Severe Disease"!=true


do you have the classification without qualifier or nothing ?

**Comment by kaledip** [comment]
This was a miss from my end. I checked as Chronic ear infection = true.
