### ISSUE TITLE
Keyboard obscures bottom of page

### ISSUE THREAD

**Issue by fenjb** [WorldHealthOrganization/smart-emcare#53]
In all questionnaires, need to close keyboard to see last questions of page - possible to allow scrolling / blank area to see all questions without needing to close?

**Comment by delcroip** [comment]
I think adding half of a screen of blank at the end of every Questionnaire will solve the issue

**Comment by ppanchal-argus** [comment]
Added blank space to the questionnaires

**Comment by kaledip** [comment]
Retested with new apk. Looks ok.
