### ISSUE TITLE
If DoB entered, show calculated age

### ISSUE THREAD

**Issue by fenjb** [WorldHealthOrganization/smart-emcare#54]
If date of birth entered, possible to show age calculation for review?
As per previously agreed rules:
- If <1week, show in days
- If <2 m, show in weeks and days
- If 2-11m, show in months
- If >=12 months, show in years and months

**Comment by delcroip** [comment]
not possible yet https://chat.fhir.org/#narrow/stream/179266-fhirpath/topic/Date.20Comparison

**Comment by delcroip** [comment]
same as #10
