### ISSUE TITLE
Danger signs 'Continue to assess sick child'

### ISSUE THREAD

**Issue by fenjb** [WorldHealthOrganization/smart-emcare#58]
Should ideally come within a pop-up about how to treat convulsing now; if pop-up not possible, should come immediately after 'convulsing now'

**Comment by delcroip** [comment]
I would propose either 
[http://hl7.org/fhir/questionnaire-item-control](https://fhir-ru.github.io/codesystem-questionnaire-item-control.html)|popup
or
[http://hl7.org/fhir/questionnaire-display-category](http://hl7.org/fhir/5.0.0-snapshot3/codesystem-questionnaire-display-category.html)|popup

**Comment by ppanchal-argus** [comment]
@delcroip @fenjb  Based on this use case.
Will this workaround do, that Continue to assess sick child is shown right below Convulsing now and either rest of the questions hide (if the logic is consistent with l2) and then the user hits the submit right after.

**Comment by kaledip** [comment]
Retested the woraround.Look fine.
