### ISSUE TITLE
UX: Respiratory rate entered disappears if press return

### ISSUE THREAD

**Issue by fenjb** [WorldHealthOrganization/smart-emcare#61]
If enter respiratory rate and press return key, number entered is deleted (child 12 months age with cough). Often users expect return key to result in moving to next field

**Comment by delcroip** [comment]
I think it is not delated, it create a second line

**Comment by ppanchal-argus** [comment]
Should be fixed now, tested in  Signs questionnaire in latest apk.

**Comment by kaledip** [comment]
Retested in Signs. working ok
