### ISSUE TITLE
Bold classification heading for >1 classification

### ISSUE THREAD

**Issue by fenjb** [WorldHealthOrganization/smart-emcare#62]
When two classifications present (Pneumonia + Fever: possible bacterial infection, in Iraq, 12 month old child), only the first (pneumonia) has a bold / large heading; fever: possible bacterial infection is small / not bold, but both should look the same

**Comment by delcroip** [comment]
it was a layout test so it is "Normal" if the pneumonia layout is fine I will work on the other (quite time consuming to adapt the formating)

**Comment by kaledip** [comment]
Retested. both classification have same font now.
