### ISSUE TITLE
Identify "Classification" = "EmCare.B23.DE28 - Measles with Eye or Mouth Complication"

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare#63]
Not showing this classification. Inputs are:
Fever = yes, Cough= Yes,  "Generalised or Localised Skin Problem" ≠ "Generalised Skin Problem" and "Measles in last 3 months" = "Yes" and Oral Sores or Mouth Ulcers" = "Mouth Sores or Mouth Ulcers - Not Deep and Extensive"

**Comment by delcroip** [comment]
CQL/decision logic fixed

**Comment by kaledip** [comment]
not yet working

**Comment by delcroip** [comment]
I see why it does not work, on all other line it is written 
```
"Generalised or Localised Skin Problem" = "Generalised Skin Problem"
```

so I didn't used `!=` , I will fix it but it looks weird

**Comment by kaledip** [comment]
Retested and working now
