### ISSUE TITLE
label for Axillary temperature and weight unclear/incomplete

### ISSUE THREAD

**Issue by gillianlevine** [WorldHealthOrganization/smart-emcare#71]
The label for axillary temperature, written below the box and "cel" is not clear to users as this is not a standard abbreviation. It should not be shortened and should be next to/part of data element label, not below the box. For weight it is also best listed next to the data element label, rather than below the box. apkversion1.0.0_dev and build 1.0.1.rc12.build.130

**Comment by delcroip** [comment]
the unit are a workarround until it is properly supported by the android-SDK, I am not sure it will be wise to change all DE if we have to change them back in few months @kaledip pleasse advise

**Comment by kaledip** [comment]
In "Measurements" all units appearing in brackets so we can close this for now.
