### ISSUE TITLE
Display of response options for Difficulty with Feeding

### ISSUE THREAD

**Issue by gillianlevine** [WorldHealthOrganization/smart-emcare#73]
Change order of responses Difficulty with feeding so that Feeding Well is first, Not Feeding well is second and Not able to feed at all is 3rd. Make boxes smaller so that all options are on one line rather than rows. 
apkversion1.0.0_dev and build 1.0.1.rc12.build.130

**Comment by kaledip** [comment]
We agreed to have severe problem to lower severe problem in options as sequence, to be in line with other questions. @gillianlevine

**Comment by kaledip** [comment]
I have updated L2 . @delcroip  pls update L3 as well.

**Comment by kaledip** [comment]
![Image](https://user-images.githubusercontent.com/122801361/227945351-476a73ec-4f91-4391-b8c3-bc6a0dc06af7.jpg)

**Comment by delcroip** [comment]
I can remove the horizontal that was required by a previous issue
