### ISSUE TITLE
Label for classification qualifiers not clear

### ISSUE THREAD

**Issue by gillianlevine** [WorldHealthOrganization/smart-emcare#81]
Classification qualifier is displaying below the box to agree or disagree with the classification- so it is read afterwards and not clearly part of the classification. Needs to be displaced right after and/or below, but on top of the agree or disagree button

**Comment by kaledip** [comment]
retested and working ok

![Image](https://user-images.githubusercontent.com/122801361/234187288-dd4ec692-475e-4040-8775-e545881a30c5.jpeg)
