### ISSUE TITLE
Classification pneumonia not met when criteria was met

### ISSUE THREAD

**Issue by gillianlevine** [WorldHealthOrganization/smart-emcare#85]
In a young infant age 10 days, respiratory rate of 60 was entered. this should prompt a second respiratory rate and if elevated of 60 or more, classification pneumonia. if no second rate is taken, first one is used, and classification should be pneumonia. Classification reached was Infection unlikely and it should have been pneumonia.

**Comment by kaledip** [comment]
RR= 66 second RR=70 Pneumonia classified. But no treatments shown.
Bundle used rc12.build269



![Image](https://user-images.githubusercontent.com/122801361/227944641-d029ecbb-5df9-4f79-8c25-6ea4da152ad2.jpg)

**Comment by delcroip** [comment]
@classification <2m was using a other questionnaire name (quiproquo with @ppanchal-argus ) I fixed the L3 side to match L4 (nothing to do on the L4)

**Comment by kaledip** [comment]
Classification Pneumonia showing up.
