### ISSUE TITLE
Length or height should not display for young infants

### ISSUE THREAD

**Issue by gillianlevine** [WorldHealthOrganization/smart-emcare#87]
If "weight cannot be measured" for young infants under 2 months, "length" should not be prompted. Currently if weight cannot be measured is selected, length is being prompted

**Comment by kaledip** [comment]
@gillianlevine  I had experienced this but it is now resolved in latest bundle. I am closing it. Let me know if you still see it is appearing.

**Comment by kaledip** [comment]
Discussed with Gillian. This is correct as per DAK but he will confirm if we need length for YI and Weight for length for YI.

**Comment by kaledip** [comment]
Weight for length wont be applicable for YI so needs to be updated in L3. Assigning to L3 now.

**Comment by kaledip** [comment]
Retested on 25/4 . Length and height ques not appearing for YI
