### ISSUE TITLE
visually assess for whether underweight should not be prompted for young infants

### ISSUE THREAD

**Issue by gillianlevine** [WorldHealthOrganization/smart-emcare#88]
If age is less than two months, if weight cannot be measured is selected, currently "Visually assess for whether underweight" is being prompted. This should not be prompted for under two month olds

**Comment by delcroip** [comment]
FYI @kaledip the condition did not took the age category into account

**Comment by kaledip** [comment]
> FYI @kaledip the condition did not took the age category into account

@delcroip  Since age category is a separate column we have not included age in conditional logic everywhere. That column needs to be referred to while creating the questionnaires.

**Comment by kaledip** [comment]
Retested and closed
