### ISSUE TITLE
Weight and/or length not appropriately mandatory

### ISSUE THREAD

**Issue by gillianlevine** [WorldHealthOrganization/smart-emcare#89]
If no weight is entered, and weight cannot be measured is entered, was able not to enter a length or height or visual assessment of underweight, nor enter prefer to enter length/height or not possible to enter length/height, and got no error messages and was able to progress to the next form. These should be mandatory.

**Comment by delcroip** [comment]
Hi, did had a profile weight ? (patient with a previous consultation ? )
