### ISSUE TITLE
inconsistent labeling for the data elements for axillary temperature and respiratory rate

### ISSUE THREAD

**Issue by gillianlevine** [WorldHealthOrganization/smart-emcare#92]
axillary temperature (second measurement) has the second measurement in brackets, whereas Respiratory rate second count has the second measurement as part of the data element label not in brackets. Form should be consistent across data elements.

**Comment by kaledip** [comment]
Renamed the elements in DAK as below-
Respiratory Rate (Second Count) (breaths per minute)
Respiratory Rate (Second Count) Not Possible

@delcroip pls change in L3 too

**Comment by kaledip** [comment]
Tested on prod. Looks ok
