### ISSUE TITLE
Weight status in Signs<2 m needs to be autocalcuated (like measured temp). It is being shown as quantity textbox and not able to add anything

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare#99]
- [x] issue reproduced
- [x] code fixed
- [x] L4 showing the <2 m  questionnaires on branch 167 @ppanchal-argus 
- [x] retest of the fix by @delcroip 
- [ ] retest by @kaledip

**Comment by delcroip** [comment]
@ppanchal-argus  I cannot test this one anymore because the <2 questionnaire are not showing anymore on dev branch 167

**Comment by kaledip** [comment]
Weight status is appearing now. Thanks @delcroip . But I also see a number calculation which is probably the z score in the Signs questions. I think it needs to be hidden. Adding screenshot.

![Image](https://user-images.githubusercontent.com/122801361/228523380-69d976bb-8ec4-48d1-9304-ac88cf6c28bf.jpg)
